version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass


  celery:
    container_name: celery
    build: ./
    volumes:
      - .:/code
    command:  celery -A core worker -l INFO
    depends_on:
      - db
      - rabbitmq
